# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Study
    url: '#study'
    weight: 20
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Skills
    url: '#skills'  
    weight: 40
  # - name: Projects
  #   url: '#projects'
  #   weight: 20
  # - name: Skills
  #   url: '#skills'  
  #   weight: 30
  # - name: Award
  #   url: '#award'
  #   weight: 50
  # - name: Honor
  #   url: '#honor'
  #   weight: 60
  # - name: Blog
  #   url: 'https://blog2.mcj.life/'
  #   weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
